name: Daily Contribution

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight (UTC)
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update File
        run: echo "Last update: $(date -u)" > update.txt

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add update.txt
          git commit -m "Daily update: $(date -u)" || echo "No changes to commit"
          git push
